<a href="https://colab.research.google.com/github/Jay-Dodhiawala/LinearRegression_fromScratch/blob/main/LinearReg_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [134]:
import torch
import numpy as np

**Creating dummy data**

In [135]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [136]:
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [137]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [138]:
num_of_input = inputs.shape[1]
num_of_target = targets.shape[1]

In [139]:
w = torch.randn(num_of_target,num_of_input, requires_grad=True)
b = torch.randn(num_of_target, requires_grad=True)
w,b

(tensor([[-0.4957,  0.0513, -0.0935],
         [-0.8788,  0.6744, -1.0569]], requires_grad=True),
 tensor([-0.2503, -0.2260], requires_grad=True))

In [140]:
def model(x):
  return x @ w.t() + b

In [141]:
preds = model(inputs)
preds

tensor([[-37.0195, -64.6363],
        [-46.8278, -88.4860],
        [-41.9231, -47.6075],
        [-52.0667, -99.9645],
        [-36.0719, -70.0995]], grad_fn=<AddBackward0>)

In [142]:
def mse(p , t):
  error = p - t
  return torch.sum(error * error) / error.numel()

In [143]:
loss = mse(preds, targets)
print(loss)

tensor(21688.4551, grad_fn=<DivBackward0>)


In [144]:
loss.backward()

In [145]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [146]:
loss = mse(model(inputs), targets)
print(loss)

tensor(14687.6035, grad_fn=<DivBackward0>)


In [147]:
w.grad.zero_()
b.grad.zero_() 

tensor([0., 0.])

In [148]:
for i in  range(100000):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()  

Checking for loss how good is our model

In [149]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(0.5072, grad_fn=<DivBackward0>)


In [150]:
preds

tensor([[ 57.1221,  70.2713],
        [ 82.2339, 100.6938],
        [118.7001, 132.9647],
        [ 21.0868,  37.0199],
        [101.9136, 119.1318]], grad_fn=<AddBackward0>)

In [151]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])