<a href="https://colab.research.google.com/github/Jay-Dodhiawala/LinearRegression_fromScratch/blob/main/LinearReg_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np

**Creating dummy data**

In [5]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [6]:
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [7]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [8]:
num_of_input = inputs.shape[1]
num_of_target = targets.shape[1]

In [9]:
w = torch.randn(num_of_target,num_of_input, requires_grad=True)
b = torch.randn(num_of_target, requires_grad=True)
w,b

(tensor([[ 0.3057,  0.2496,  0.7511],
         [ 0.3560,  0.2249, -1.6447]], requires_grad=True),
 tensor([-0.2754, -0.6957], requires_grad=True))

In [10]:
def model(x):
  return x @ w.t() + b

In [11]:
preds = model(inputs)
preds

tensor([[ 71.0647, -30.3572],
        [ 97.5832, -53.7642],
        [103.3373, -34.9726],
        [ 69.4319, -15.5621],
        [ 97.3616, -69.6661]], grad_fn=<AddBackward0>)

In [12]:
def mse(p , t):
  error = p - t
  return torch.sum(error * error) / error.numel()

In [13]:
loss = mse(preds, targets)
print(loss)

tensor(10362.4854, grad_fn=<DivBackward0>)


In [14]:
loss.backward()

In [15]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [16]:
loss = mse(model(inputs), targets)
print(loss)

tensor(7256.0952, grad_fn=<DivBackward0>)


In [17]:
w.grad.zero_()
b.grad.zero_() 

tensor([0., 0.])

In [18]:
for i in  range(1000):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()  

Checking for loss how good is our model

In [19]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(37.4434, grad_fn=<DivBackward0>)


In [20]:
preds

tensor([[ 57.0930,  70.9305],
        [ 82.5603,  94.6900],
        [118.0044, 145.5580],
        [ 20.9768,  40.6516],
        [102.5407, 106.4766]], grad_fn=<AddBackward0>)

In [21]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

# **Now i am trying to do the same thing but with libraries and with big dataset**


In [22]:
import numpy as np


In [23]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


In [24]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [25]:
train_ds = TensorDataset(inputs, targets)
train_ds[:5]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [26]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [32]:
from torch import nn

In [31]:
for a, b in train_dl:
  print(a)
  print(b)
  break

tensor([[102.,  43.,  37.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [101.,  44.,  37.],
        [ 87., 134.,  58.]])
tensor([[ 22.,  37.],
        [ 82., 100.],
        [118., 134.],
        [ 21.,  38.],
        [119., 133.]])


In [34]:
model = nn.Linear(3,2)
list(model.parameters())

[Parameter containing:
 tensor([[-0.4096,  0.2006, -0.0515],
         [ 0.3751, -0.1110,  0.0447]], requires_grad=True),
 Parameter containing:
 tensor([ 0.2112, -0.3016], requires_grad=True)]

In [35]:
preds = model(inputs)
preds

tensor([[-18.4658,  21.5693],
        [-22.7082,  26.9300],
        [-11.5313,  20.0534],
        [-34.8513,  34.8449],
        [-12.4004,  18.0570],
        [-19.0761,  22.0555],
        [-22.9604,  27.0858],
        [-11.9925,  20.4733],
        [-34.2410,  34.3588],
        [-12.0423,  17.7266],
        [-18.7180,  21.7251],
        [-23.3185,  27.4162],
        [-11.2791,  19.8976],
        [-35.2094,  35.1753],
        [-11.7901,  17.5708]], grad_fn=<AddmmBackward0>)

In [36]:
from torch.functional import F 

In [37]:
loss_fun = F.mse_loss

In [38]:
loss = loss_fun(model(inputs), targets)

In [39]:
loss


tensor(8045.1416, grad_fn=<MseLossBackward0>)

In [40]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [41]:
def fit(num_runs, model, loss_fn, opt, train_dl):

  for run in range(num_runs):
    for xb, yb in train_dl:
      pred = model(xb)
      loss = loss_fn(pred, yb)
      loss.backward()
      opt.step()
      opt.zero_grad()
    if(run+1)%10 == 0:
      print('Epoch [{}/{}], Loss: {:.4f}'.format(run+1, num_runs, loss.item()))

In [42]:
fit(100, model, loss_fun, opt, train_dl)

Epoch [10/100], Loss: 404.5144
Epoch [20/100], Loss: 158.1380
Epoch [30/100], Loss: 149.4172
Epoch [40/100], Loss: 186.2939
Epoch [50/100], Loss: 94.5033
Epoch [60/100], Loss: 55.0494
Epoch [70/100], Loss: 33.4058
Epoch [80/100], Loss: 58.0844
Epoch [90/100], Loss: 33.3874
Epoch [100/100], Loss: 18.7099
