<a href="https://colab.research.google.com/github/Jay-Dodhiawala/LinearRegression_fromScratch/blob/main/LinearReg_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [71]:
import torch
import numpy as np

**Creating dummy data**

In [72]:
inputs = np.array([[73., 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]])

In [73]:
targets = np.array([[56., 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]])

In [74]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [75]:
num_of_input = inputs.shape[1]
num_of_target = targets.shape[1]

In [76]:
w = torch.randn(num_of_target,num_of_input, requires_grad=True)
b = torch.randn(num_of_target, requires_grad=True)
w,b

(tensor([[-0.7026,  0.2465,  0.9425],
         [ 0.5675,  0.4340,  1.0378]], requires_grad=True),
 tensor([ 0.7469, -0.6866], requires_grad=True))

In [77]:
def model(x):
  return x @ w.t() + b

In [78]:
preds = model(inputs)
preds

tensor([[  6.4989, 114.4407],
        [ 18.8207, 155.5625],
        [ 27.3159, 167.0297],
        [-25.4481, 114.2543],
        [ 41.9052, 152.7772]], grad_fn=<AddBackward0>)

In [79]:
def mse(p , t):
  error = p - t
  return torch.sum(error * error) / error.numel()

In [80]:
loss = mse(preds, targets)
print(loss)

tensor(3392.5679, grad_fn=<DivBackward0>)


In [81]:
loss.backward()

In [82]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [83]:
loss = mse(model(inputs), targets)
print(loss)

tensor(2369.0010, grad_fn=<DivBackward0>)


In [84]:
w.grad.zero_()
b.grad.zero_() 

tensor([0., 0.])

In [85]:
for i in  range(10000):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()  

Checking for loss how good is our model

In [86]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(0.5159, grad_fn=<DivBackward0>)


In [87]:
preds

tensor([[ 57.2898,  70.1925],
        [ 82.1292, 100.7437],
        [118.6716, 132.9763],
        [ 21.0655,  37.0297],
        [101.9415, 119.1202]], grad_fn=<AddBackward0>)

In [88]:
targets

tensor([[ 56,  70],
        [ 81, 101],
        [119, 133],
        [ 22,  37],
        [103, 119]])